### ISSUE TITLE
NSFW! 8muses.com, pornhub.com

### ISSUE THREAD

**Issue by uBlock-user** [X01X012013/AdBlockProtector#61]
an iframe adbanner placeholder, adblock notice appears on the extreme left side which was already blocked by an appropriate CSS selector via uBlock as long as the script is running.

![](https://i.gyazo.com/1a2d5f33ec75dedd19246e71b98780a1.png)

![](https://i.gyazo.com/1ae97c215b917bad59ff600363a37edd.png)

Besides these two, when I right click, open the context menu and click on "Block Element" which is uBlock's option, the element hiding selector mod won't open because of the script. Happens in both TamperMonkey and ViolentMonkey.

**Comment by X01X012013** [comment]
Thanks for your report, I'll have a look. The selector might be caught in a generic filter.

**Comment by X01X012013** [comment]
OK, those banners can be blocked with uBlock Origin, every other time it sends you to a block page... Do you have a solution for that?

**Comment by uBlock-user** [comment]
Read again, those two things are already blocked. Your script loads them. If I disable the script, they don't appear.

**Comment by X01X012013** [comment]
Hi, I figured out what's going on. `a.crashScript` seems to break uBlock Origin's element picker. I have commented out calls to this function for now. This is fixed in 6.44.
I was confused because my cosmetic filter was not on, and I see the banner no matter what. Also, every other time it sends me to the block page, does it happen to you? Which custom filters are you using?

**Comment by uBlock-user** [comment]
>  Also, every other time it sends me to the block page, does it happen to you?

Yes, that's the most nastiest thing I'm facing with the website since a long time.

I'm using : 

````
8muses.com##.a-image
@@||jsdelivr.net^$domain=8muses.com
8muses.com##.top-warning
@@||ampproject.org^$image,domain=8muses.com
8muses.com##script:inject(abort-on-property-read.js, _$_eb9c)
||$third-party,domain=8muses.com

**Comment by X01X012013** [comment]
@uBlock-user 
OK, I'll see if I can detect keywords and do an auto-refresh. 
I see which script is doing it, but patching it breaks images. One day... one day browsers will support `onbeforescriptexecute`. 
For now, only one website is using `a.crashScript` hack (it does have the side effect of breaking uBO element picker, but that website is tested and everything else works well), I disabled all other calls that are copied from AAK.

**Comment by uBlock-user** [comment]
`8muses.com##script:inject(abort-on-property-read.js, _$_eb9c)`

^ That one partially fixed the block page issue, for me, the block page only appears when I'm browsing the home page, but when I'm viewing images of a comic back and forth.

**Comment by X01X012013** [comment]
@uBlock-user Looks like that is the case without this rule. That variable is never defined.

**Comment by uBlock-user** [comment]
@X01X012013 Can you use chrome.webRequest.onBeforeRequest listener in place of `onbeforescriptexecute` ?

**Comment by X01X012013** [comment]
@uBlock-user 
Thanks, I'll look into it. 
I added auto-refresh so block screen will be "skipped". You will only see it for less than a second. I also added `8muses.com##.top-warning` to my List, as far as I tested it, other rules seems redundant.

**Comment by uBlock-user** [comment]
Alright, you might as well close the issue now.

**Comment by X01X012013** [comment]
Looks like `chrome.webRequest.onBeforeRequest` is only available to extensions, and Userscript can't access it. 
Thanks again for your report. I'll close this issue now.

**Comment by uBlock-user** [comment]
@X01X012013 Tampermonkey can use it since v2.4, so can you leverage it via TM ?

**Comment by X01X012013** [comment]
Do you have a link? I couldn't find anything about it... 
![image](https://cloud.githubusercontent.com/assets/7283682/23271385/858b7704-f9b4-11e6-8414-ad2ddab654d8.png)

**Comment by uBlock-user** [comment]
link to what ? I found about TM and VM's permissions via their extension manifest files. I don't know how to leverage them into JS though, sorry.

**Comment by X01X012013** [comment]
@uBlock-user 
I'm not exactly sure how extensions work, as far as I know, there isn't a way to block in-line script with Userscript except the `a.crashScript` hack.

**Comment by uBlock-user** [comment]
Hey @derjanb, can you englighten us on how to use `chrome.webRequest` and `chrome.webRequestBlocking` API in userscripts ? TamperMonkey supports these and has permissions which can be found in the manifest.json of TM, so we're wondering.

**Comment by X01X012013** [comment]
I'll reopen this issue since the discussion hasn't finish. 

What we really need is intercept loading of the main document and modify it. Subsequent request can be blocked by editing `XMLHttpRequest` constructor.

**Comment by X01X012013** [comment]
I'm a bit busy lately, I'll have another look at this when I have time. The adblock detection script is highly obfuscated, but I think I can find the way to properly fix this.

**Comment by uBlock-user** [comment]
Alternatively, uBO users can simply add these filters and forget about it : 

````
||8muses.com^$inline-script
@@||8muses.com/comix/picture^$inline-script

**Comment by X01X012013** [comment]
@uBlock-user I was thinking about that 👍 Added to my List.

**Comment by uBlock-user** [comment]
Also blocking inline-script neutralizes the need to inject cosmetic filters, so remove any cosmetic filters you added for 8muses too.

**Comment by X01X012013** [comment]
@uBlock-user Yes, I did that.

**Comment by uBlock-user** [comment]
btw `pornhub.com`'s launching popunders based on a cookie check just like `hanime.tv` was doing. Can you look into that ?

**Comment by X01X012013** [comment]
@uBlock-user 
I don't know how they did it, but it goes right through my `a.filter()`. I Googled the script, it sells for like $900 per year, definitely some solid stuff. And they seems to be customized for each site so a generic solution isn't possible (or at least very hard). For `pornhub.com`, the solution is: 
```JavaScript
if (a.domCmp(["pornhub.com"])) {
    //NSFW! Patch open()
    a.win.open = function (arg) {
        if (arg.includes("pornhub.com")) {
            a.win.location.href = arg;
        }
    };
}
```

**Comment by X01X012013** [comment]
It's added to 6.49. 
I'm pretty confident that it isn't possible to intercept main html with Userscript, and since I'll still receive notification for closed issues, I'll close this issue now.

**Comment by uBlock-user** [comment]
@X01X012013 Actually, the alternative to this solution is pretty simple. Delete, `FPSRN` named cookie and the popunders will stop. I wonder if you can lock cookies for a website in JS as in don't allow the website to put in any new cookies, that can used against such a script.

**Comment by X01X012013** [comment]
@uBlock-user 
For locking down a specific cookie, it is not impossible, but it's very complex. 
Locking down all cookies is simpler, but not simpler than my solution above. 
I'm wondering why uBO doesn't have a `$no-cookie` or `(cookie-inject.js, name, value)`

**Comment by uBlock-user** [comment]
> Locking down all cookies is simpler, but not simpler than my solution above.

That would be preferable as in a consistent solution. pornhub dev is known to stalk these issue trackers on github and make new changes every once in a while. That's why I would prefer to block all cookies from `pornhub.com` from entering my browser if possible via JS. Your solution is considerably solid, so it would be difficult for that guy to bypass this one, we'll see what he does further.

uBO doesn't have the scriptlet because gorhill hasn't added it or given much preference to it yet. He simply did the opposite though, he sets the cookie value high of `FastPopSessionRequestNumber` to a higher number to defeat the script which also works, but the pornhub dev introduced another cookie named `FPSRN`, so're back to where we started, that's why I would prefer to block cookies once and for all via scriptlet to end this game of cat and mouse.

**Comment by X01X012013** [comment]
I don't see how locking down all cookies is better since it is detectable, and can break other things. 
I currently allow content script to detect my tampered `open()`, but it's just a switch flip to make it undetectable. 

Yes, there is still ways around my `open()` even if I activated `a.protectFunc()`, but the way around locked cookies is easier.

**Comment by uBlock-user** [comment]
> I don't see how locking down all cookies is better since it is detectable, and can break other things.

I'm talking specifically about pornhub. Blocking all cookies will only stop you from logging, everything else works fine and will deter the dev from introducing new cookies and stopping that would force him to come up with a new strategy. Basically we're plugging that hole(no pun intended)

> I have to say we'll never end this cat and mouse game

Oh believe me, it would end, if the dev is forced to take a drastic action and change the entire outlook of the website which a dev will rarely do, it's not worth his time, besides, pornhub is a high profile porn entertainment website and the dev makes millions as not everyone makes use of adblockers and userscripts, only handful do and he's not gonna change the entire website just to compete with folks who intend on blocking his measures.

**Comment by X01X012013** [comment]
Well, they can just tell you if you don't enable cookies you'll get pop-up every click. It's like 3 lines of code. 

If you really want, you can set it in your browser settings. And for stopping tracking, your session is destroyed when you exit incognito mode anyway. 

(It's in Chinese but it should look the same)
![image](https://cloud.githubusercontent.com/assets/7283682/23319858/911cbc40-fa95-11e6-93c0-b0aad1fb5fb8.png)

From my JavaScript experience, I think my fix is more of a pain to bypass, since `window.open()` is the only way to pop-up, where for cookies, LocalStorage is a drop-in replacement.

**Comment by uBlock-user** [comment]
I know about that, I am hoping if I can kill it with JS then that's good enough for me, otherwise ultimately if it comes down to blocking site cookies via the browser, I would do it. It's a matter of preference for me. Your fix is solid as I mentioned before, so we will wait and see if something new comes up.

**Comment by X01X012013** [comment]
Well, I can tell you how, but I don't really see the point of putting it into AdBlock Protector. 
```JavaScript
// ==UserScript==
// @name         Block cookies and/or LocalStorage
// @version      1
// @description  try to take over the world!
// @author       X01X102013
// @match        http://*.example.com/*
// @grant        none
// @run-at       document-start ==/UserScript==

(function () {
    "use strict";
    //Block all cookies
    Object.defineProperty(document, "cookie", {value: ""});
    //Block LocalStorage
    delete window.localStorage;
    delete window.sessionStorage;
    delete widnwo.Storage;
})();
```

**Comment by derjanb** [comment]
> Hey @derjanb, can you enlighten us on how to use chrome.webRequest and chrome.webRequestBlocking API in userscripts ? TamperMonkey supports these and has permissions which can be found in the manifest.json of TM, so we're wondering.

@uBlock-user The webRequest API is used only internally by Tampermonkey and there is no way for a userscripts to access it.
If you could specify an API how would it look like? What functionality would it provide, that can't be done with *blocker extensions? Please consider that the communication between userscripts and the Tampermonkey main code is asynchronous. This means everything that should be done with the webRequest API needs to be communicated to the main code before the web requests are happening.

**Comment by X01X012013** [comment]
@derjanb 
Hi, thanks for replying 😄 

> If you could specify an API how would it look like?
`TM_onBeforeRequest(callback)` Where `callback` takes in the URL of the request, if `callback` returns `true`, this request is blocked. 
`TM_onAfterRequest(callback)` Where `callback` takes in an event object, and can modify the response text and statue. I'm not sure if this is possible, I'm not very sure how extensions work. Looks like HTML is parsed while loading, maybe we need another API like `TM_onBeforeHTMLParse`? 

> What functionality would it provide, that can't be done with *blocker extensions? 
`TM_onBeforeRequest(callback)` allows RegExp or other complex filtering logic. This would be the answer to detection script changing its name automatically every day. 
`TM_onAfterRequest(callback)` will allow patching in-line script, which isn't currently possible on Chromium based browsers. And when uBO block in-line scripts, it either blocks all or none. It also allows modifying XHR responses, uBO only allow redirecting to empty responses. 

> This means everything that should be done with the webRequest API needs to be communicated to the main code before the web requests are happening. 
Maybe a `@grant delayFirstWebRequest` statement that will cause the webRequest for the main HTML to be delayed until `TM_onAfterRequest(callback)` is called?

**Comment by uBlock-user** [comment]
@derjanb Can the userscript communicate to TM first and then TM relays the request to Chrome ?

**Comment by X01X012013** [comment]
@uBlock-user I think the permissions need to be listed when compiling the extension, so if you ever need it, you would need to ask for it when installing.

**Comment by uBlock-user** [comment]
FYI, pornhub and others are using a script called UAParser which fetches OS name , browsers name, plugins and all that shit. Need to lock that variable which also stop popups.
 
example `pornhub.com##script:inject(abort-on-property-write.js, UAParser)`

Can be used as an alternative solution

**Comment by derjanb** [comment]
> TM_onBeforeRequest(callback) Where callback takes in the URL of the request, if callback returns true, this request is blocked.

>Maybe a @grant delayFirstWebRequest statement

As I said the communication with the main code is asynchronous and it's not possible to pause a request and continue it later. When the requests happens all information whether to cancel or continue the requests needs to be sent to the main code already.

So it would only be possible to setup something like regular expression based rules whether to block, redirect or stop a request.

**Comment by X01X012013** [comment]
@derjanb 
Is it possible to not redirect, but change the response received? And can we do this for the main HTML file?

**Comment by derjanb** [comment]
@jspenguin2017 @uBlock-user If you're interested, please check https://github.com/Tampermonkey/tampermonkey/issues/397#issuecomment-299949037 regarding a draft implemented that allows the use the webRequest API at user scripts.
